# this is for running the dev environment for the project.
version: '2'

services:

  # the app in this project
  app:
    build:
      context: .
      dockerfile: dockerfile-dev
    ports:
      - 8002:80
    volumes:
      - .:/var/app
    environment:
      REDIS_URL: redis://6379
  
  # just because...
  redis:
    image: redis:alpine