# this is for running the dev environment for the project.
version: '2'

services:

  # the app in this project
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 8002:80
    depends_on:
      - redis
    volumes:
      - .:/var/app
    environment:
      REDIS_URL: redis:6379
  
  # just because...
  redis:
    image: redis:alpine
  
  # cuz why not?
  docs:
    image: swaggerapi/swagger-ui
    ports:
      - 8003:8080
    environment:
      API_URL: "http://localhost:8002/swagger.json"