# adapted from: https://github.com/TrafeX/docker-php-nginx/blob/master/Dockerfile
FROM php:7.1-fpm-alpine

LABEL Maintainer="Evan Villemez <evillemez@gmail.com>" \
      Description="Example Silex app using nginx 1.10 & PHP-FPM 7.1 based on Alpine Linux."

# install other deps
RUN apk --no-cache add nginx supervisor curl

# override configs
COPY conf/fpm-pool.conf /etc/php7/php-fpm.d/zzz_custom.conf
COPY conf/php.ini /etc/php7/conf.d/zzz_custom.ini
COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY conf/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

WORKDIR /var/app

# install dev env tools: git/composer/cs-fixer
RUN apk --no-cache add zlib-dev git zip
RUN curl -sS https://getcomposer.org/installer | php \
        && mv composer.phar /usr/local/bin/ \
        && ln -s /usr/local/bin/composer.phar /usr/local/bin/composer

# start supervisor & expose ports
USER root
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
EXPOSE 80 443
